name: Rust Build Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Kodunu GitHub sunucusuna çeker
    
    - name: Build
      run: cargo build --verbose # Kodun derlenip derlenmediğini kontrol eder
      
    - name: Run tests
      run: cargo test --verbose  # Yazdığın testleri çalıştırır
